project:
  type: website
  output-dir: docs
  
website:
  title: "Drew Day's Website and Blog"
  description: "Musings and lessons on statistical analysis and programming with a focus on epidemiology, bioinformatics, and health economics"
  site-url: https://drewdstat.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - blogposts.qmd
      - pkgguides.qmd
      - mountains.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/drewbday
      - icon: github
        href: https://github.com/drewdstat/drewdstat.github.io
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Drew Day"

format:
  html:
    theme: lux
    toc: true

editor: source

